spring:
  profiles:
    active: dev

---
server:
  port: 8002
spring:
  application:
    name: AIGOU-PRODUCT-APPLICATION
  profiles: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/


---
server:
  port: 8011
spring:
  application:
    name: AIGOU-PRODUCT-APPLICATION-TEST
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aigou_test
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/  
  instance:
    prefer-ip-address: true 
mybatis-plus:
  mapper-locations: classpath:cn/itsource/aigou/mapper/*Mapper.xml
  type-aliases-package: cn.itsource.aigou.domain,cn.itsource.aigou.query 
