spring:
  profiles:
    active: dev

---
server:
  port: 8001
spring:
  application:
    name: EMPLOYEE-PROVIDER
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip

---
server:
  port: 8010
spring:
  application:
    name: EMPLOYEE-PROVIDER-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true #显示客户端真实ip